function y = cic(x)
%CIC Filters input x and returns output y.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and DSP System Toolbox 9.9.
% Generated on: 20-May-2021 22:28:45

%#codegen

% To generate C/C++ code from this function use the codegen command.
% Type 'help codegen' for more information.

persistent Hd;

if isempty(Hd)
    
    intf    = 25;  % Interpolation Factor
    diffd   = 1;   % Differential Delay
    numsecs = 5;   % Number of Sections
    
    Hd = dsp.CICInterpolator( ...
        'InterpolationFactor', intf, ...
        'DifferentialDelay', diffd, ...
        'NumSections', numsecs);
end

s = fi(x,1,16,15,'RoundingMethod','Round','OverflowAction','Saturate');
y = step(Hd,s);


% [EOF]
